import Link from 'next/link';
import './globals.css'; // Assuming a global CSS file for styling

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-white text-lg font-bold">
              Debt Collection Agency
            </div>
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="text-gray-300 hover:text-white">
                  Dashboard
                </Link>
              </li>
              <li>
                <Link href="/customers" className="text-gray-300 hover:text-white">
                  Customers
                </Link>
              </li>
              <li>
                <Link href="/interactions" className="text-gray-300 hover:text-white">
                  Interactions
                </Link>
              </li>
              <li>
                <Link href="/live" className="text-gray-300 hover:text-white">
                  Live
                </Link>
              </li>
            </ul>
          </div>
        </nav>
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
